### ISSUE TITLE
Active Route Test

### ISSUE THREAD

**Issue by rgleason** [BerndCirotzki/raymarine_autopilot_pi#10]
I set a premade route active, autopilot_raymarine and then started Marco Bergman's ais-simulation.exe
https://github.com/marcobergman/ais_simulation
and finally got things right and recorded a session (I had autopilot_route enabled at first, which messed up things!)

I hope I am doing this right.
![1-Turn-at-wpt](https://user-images.githubusercontent.com/2363959/214097480-e8d69257-dd2d-493f-bf0b-35c62bf2d5ac.png)

 
![2-Continue](https://user-images.githubusercontent.com/2363959/214097497-4e107f47-a08d-455d-8699-78765e0b473d.png)

![3-Overshoot](https://user-images.githubusercontent.com/2363959/214097523-0565a098-df50-4c9a-9376-147f9009f88d.png)

**Comment by rgleason** [comment]
![4-Finally-turn](https://user-images.githubusercontent.com/2363959/214097566-57a3256b-1e46-4625-b437-1e4b522a799f.png)
![5-Approach-next-wpt](https://user-images.githubusercontent.com/2363959/214097582-39289eca-a927-416c-8df4-41a9e1b3f505.png)
![6-Overshoot-again](https://user-images.githubusercontent.com/2363959/214097599-80937c7f-7f92-4b11-86e4-27081933c292.png)

**Comment by rgleason** [comment]
![7-Turn-and-miss-next-wpt](https://user-images.githubusercontent.com/2363959/214097676-dc31bad9-be31-4f5d-b9c1-ac7639714b63.png)
![8-approach-next-wpt](https://user-images.githubusercontent.com/2363959/214097700-fff92a23-4aa8-465b-94cb-44ebac766dfc.png)
![9-next-wpt](https://user-images.githubusercontent.com/2363959/214097719-61826120-b191-4a60-9680-d548fe5b14e7.png)

**Comment by rgleason** [comment]
![10-Overshoot-and-turn-to-wpt](https://user-images.githubusercontent.com/2363959/214097762-3c4ff231-c3e1-4c8b-ab76-31791bf0f9ed.png)
![11-continue-on-same-course](https://user-images.githubusercontent.com/2363959/214097788-da091b12-b3bd-4d64-9614-080b1630931c.png)

Maybe I need to adjust something?

**Comment by BerndCirotzki** [comment]
Hello Rick,

The Autopilot sends Seatalkmessages every second( Statusmessages ) , that must be translated form NMEA/Seatalk convert to NMEA in this Format: 
$STALK,84,26,A2,88,40,00,FE,02,06*15 ( This is a Standby )
The Plugin wants this Sentence ever Second. after 10 Seconds No Message received, the Plugin shows "-------". ( No Autopilot activ)
The Autopilot receives only Keystroke-Seatalk sentences, from the Plugin. The must be converted from NMEA/Seatalk Converter from NMEA to Seatalk.
(Try to push a Button (Auto) on the Pluin an you See Senteces in the NMEA Output Window)

<GREEN>16:41:32 (virtual) $STALK,86,21,01,FE*4E<0x0D><0x0A>
<BLUE>--> 16:41:32 (COM10) $STALK,86,21,01,FE*4E<0x0D><0x0A>

Now you see The receive and the Send Sentence is "STALK" .. thats the reason you can change the names in the preferencedialog.
Because Opencpn mirriors every incoming Message back to the Serial Port, when it is defined as an output to Autopilot.
( for a long time I wore an Issue for that, Not to Send the same message back to the Serial port, where it comes from. Because that makes no sence.)
( Also I found out, that Opencpn not receives all NMEA Sententences from the Serial Port, when it is an Outputport, and there is no Output filter Set.
It seems that then there is too much traffic for Opencpn.)


The RMB, APB and XTE you can send out to the NMEA/Seatalk Converter, when it will be translated, or use an other Serial output port and Send the
Sentences to the NMEA Input from Raymarine Autopilot. no matter.

With the keystrokes, on Plugin you only tell the Raymarine Autopilot to change his Status.
go to Auto or go to Windmode, or to Trackmode.

When you tell the Autopilot to go to track mode, he want to get RMB,APB, XTE Sentences to accept this Mode. otherwise it will cause an Error,
with the Autopilot also sends back in the $STALK,84 .... Sentence to the Plugin. The plugin the shows "No Waypoint"

You can not test the function as you like. sorry :-)

Bernd

**Comment by rgleason** [comment]
I am going to close this now. Thanks.
